[package]
name = "mkbootimg"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/tinted-software/mkbootimg"

[lib]
name = "bootimg"
path = "rust/bootimg.rs"

[dependencies]
zerocopy = { version = "0.7.35", features = ["derive"] }
